### ISSUE TITLE
[FIX] Variable naming pickings vs picking

### ISSUE THREAD

**Issue by odoo-mastercore** [ingadhoc/stock#372]
https://github.com/ingadhoc/stock/blob/1978a3340cb58d60d8f868d1d11d2d3b3779dd87/stock_voucher/wizards/stock_immediate_transfer.py#L26

**Comment by maq-adhoc** [comment]
@odoo-mastercore fix here https://github.com/ingadhoc/stock/commit/2fe0ccabf7f3ea3c1ac8e79a7d99f9ab5cd3611f
